/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        "on-primary": "#ffffff",
        "primary-container": "var(--primary-dark)",
        "on-primary-container": "#f7fff2",
        "primary-fixed": "#7ffc97",
        "primary-fixed-dim": "#62df7d",
        "inverse-primary": "#62df7d",
        secondary: "var(--cyan)",
        "on-secondary": "#ffffff",
        "secondary-container": "#57dffe",
        "on-secondary-container": "#006172",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        tertiary: "var(--muted)",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6a758a",
        "on-tertiary-container": "#fefcff",
        "tertiary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#bcc7de",
        error: "var(--critical)",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "var(--surface)",
        "surface-dim": "var(--surface-container)",
        "surface-bright": "var(--surface-container-low)",
        "surface-container-lowest": "var(--surface)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-high)",
        "surface-variant": "var(--surface-container-high)",
        "on-surface": "var(--text)",
        "on-surface-variant": "var(--muted)",
        "on-background": "var(--text)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline)",
        "inverse-surface": "var(--surface-container-high)",
        "inverse-on-surface": "var(--text)",
        "surface-tint": "var(--primary)",
        background: "var(--background)",
        /* Admin console palette — driven by data-theme CSS vars */
        adm: {
          bg: "var(--adm-bg)",
          surface: "var(--adm-surface)",
          raised: "var(--adm-surface-2)",
          border: "var(--adm-border)",
          text: "var(--adm-text)",
          muted: "var(--adm-muted)",
          primary: "var(--adm-primary)",
          "primary-strong": "var(--adm-primary-strong)",
          ok: "var(--adm-ok)",
          warn: "var(--adm-warn)",
          danger: "var(--adm-danger)",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        display: ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "title-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "label-md": ["Manrope"],
        "label-sm": ["Manrope"],
      },
      fontSize: {
        display: ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "700" }],
      },
      keyframes: {
        "scan-line": {
          "0%": { top: "0%", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "50%": { opacity: "1", transform: "scale(1.02)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(0,107,44,0.15)" },
          "50%": { boxShadow: "0 0 30px rgba(0,107,44,0.3)" },
        },
        "pulse-row": {
          "0%, 100%": { backgroundColor: "transparent" },
          "50%": { backgroundColor: "rgba(0,168,150,0.10)" },
        },
      },
      animation: {
        "scan-line": "scan-line 3s cubic-bezier(0.4, 0, 0.2, 1) infinite",
        "spin-slow": "spin-slow 3s linear infinite",
        shimmer: "shimmer 1.5s infinite",
        fadeIn: "fadeIn 0.5s ease-out",
        fadeOut: "fadeOut 0.3s ease-out forwards",
        bounceIn: "bounceIn 0.4s cubic-bezier(0.22,1,0.36,1)",
        slideUp: "slideUp 0.5s ease-out",
        pulseGlow: "pulseGlow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
