export const APP_STATES = {
  INITIALIZING: "INITIALIZING",
  FIRST_TIME_USER: "FIRST_TIME_USER",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  AUTHENTICATED_CITIZEN: "AUTHENTICATED_CITIZEN",
  AUTHENTICATED_ADMIN: "AUTHENTICATED_ADMIN",
  AUTHENTICATED_WORKER: "AUTHENTICATED_WORKER",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  NETWORK_ERROR: "NETWORK_ERROR",
  STARTUP_ERROR: "STARTUP_ERROR",
  RECONNECTING: "RECONNECTING",
};

export const statusLabels = {
  submitted: "Report Received",
  analyzing: "Analyzing...",
  ai_analyzed: "AI Checked",
  analysis_failed: "Analysis Failed",
  duplicate: "Duplicate Detected",
  under_review: "Authority Review",
  assigned: "Cleanup Team Assigned",
  en_route: "Team En Route",
  cleanup_in_progress: "Cleanup Started",
  verification: "Verification",
  resolved: "Resolved",
  reopened: "Reopened",
};

export const roleRoutes = {
  citizen: "/home",
  admin: "/admin/dashboard",
  super_admin: "/admin/dashboard",
  ward_officer: "/admin/dashboard",
  sanitation_supervisor: "/admin/dashboard",
  cleanup_worker: "/worker/home",
};

export const severityColors = {
  low: "var(--severity-low)",
  medium: "var(--severity-medium)",
  high: "var(--severity-high)",
  critical: "var(--severity-critical)",
};

export const onboardingSlides = [
  {
    id: "onboard-1",
    label: "Step 1 · Capture",
    title: "Spot waste in seconds",
    body: "Snap a photo or a short video — SwachhLens pins the exact spot and starts working right away.",
  },
  {
    id: "onboard-2",
    label: "Step 2 · Analyze",
    title: "AI sorts the mess for you",
    body: "Waste type, size and urgency are identified instantly, so the right team gets dispatched faster.",
  },
  {
    id: "onboard-3",
    label: "Step 3 · Track",
    title: "Watch it get cleaned up",
    body: "Follow every step — from your report to a verified clean area — on a live timeline.",
  },
];

export const permissionCopy = {
  camera: {
    title: "Allow camera access",
    body: "SwachhLens uses your camera to capture waste evidence for AI analysis and cleanup verification.",
    primary: "Allow Camera",
    secondary: "Not Now",
  },
  gallery: {
    title: "Allow photo access",
    body: "Choose an existing waste photo or video to submit with your report.",
    primary: "Choose Media",
    secondary: "Not Now",
  },
  location: {
    title: "Allow location access",
    body: "SwachhLens uses your location to identify where the waste issue is and send the report to the appropriate municipal team.",
    primary: "Allow Location",
    secondary: "Not Now",
  },
  device: {
    title: "Allow access to your device",
    body: "SwachhLens needs location, camera, video, and file/media access so you can capture waste accurately and submit the report to the right cleanup team.",
    primary: "Allow All Access",
    secondary: "Not Now",
  },
  notifications: {
    title: "Stay updated about your report",
    body: "Enable notifications to know when a cleanup team is assigned or your report is resolved.",
    primary: "Enable Notifications",
    secondary: "Not Now",
  },
};

export const demoProfiles = {
  citizen: {
    uid: "user-citizen",
    name: "Ananya Das",
    email: "citizen@swachhlens.app",
    phone: "+919876543210",
    role: "citizen",
    isActive: true,
    locationName: "Bhubaneswar, Unit 4",
    createdAt: "2026-08-01T09:00:00+05:30",
    updatedAt: "2026-08-07T09:00:00+05:30",
  },
  admin: {
    uid: "user-admin",
    name: "Command Center Admin",
    email: "admin@swachhlens.com",
    phone: "+919812340000",
    role: "super_admin",
    isActive: true,
    locationName: "Region North",
    createdAt: "2026-07-20T10:00:00+05:30",
    updatedAt: "2026-08-07T09:00:00+05:30",
  },
  cleanup_worker: {
    uid: "user-worker",
    name: "Team Alpha",
    email: "worker@swachhlens.app",
    phone: "+919800001111",
    role: "cleanup_worker",
    isActive: true,
    locationName: "Ward 12",
    createdAt: "2026-07-25T10:00:00+05:30",
    updatedAt: "2026-08-07T09:00:00+05:30",
  },
};

export const mockNotifications = [
  {
    id: "note-1",
    title: "Team assigned",
    body: "Sanitation Team 07 has been assigned to your latest report.",
    time: "12 min ago",
  },
  {
    id: "note-2",
    title: "Hotspot alert",
    body: "Plastic waste complaints are rising near Unit 4 Market.",
    time: "1 hr ago",
  },
];

export const mockTeams = [
  {
    id: "team-07",
    name: "Sanitation Team 07",
    leader: "Rakesh Nayak",
    members: 4,
    vehicle: "Mini Tipper",
    currentLocation: "Ward 12 Depot",
    availability: "available",
    currentTask: null,
    tasksCompletedToday: 6,
    status: "available",
    etaMinutes: 12,
    distanceKm: 1.8,
    aiMatchScore: 94,
  },
  {
    id: "team-03",
    name: "Rapid Response 03",
    leader: "Farah Khan",
    members: 3,
    vehicle: "Flatbed",
    currentLocation: "Unit 1 Market",
    availability: "assigned",
    currentTask: "REP-992A",
    tasksCompletedToday: 4,
    status: "en_route",
    etaMinutes: 18,
    distanceKm: 3.1,
    aiMatchScore: 82,
  },
  {
    id: "team-alpha",
    name: "Team Alpha",
    leader: "S. Patnaik",
    members: 4,
    vehicle: "Mini Tipper",
    currentLocation: "1420 Main St",
    availability: "assigned",
    currentTask: "REP-28491",
    tasksCompletedToday: 3,
    status: "assigned",
    etaMinutes: 15,
    distanceKm: 1.2,
    aiMatchScore: 91,
  },
];

export const mockReports = [
  {
    id: "REP-28491",
    userId: "user-citizen",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCNtZ3KEcNO2H348nP4tNkYQ47B8Z8CQF2JJBUDDiGfNHwXQX3P35QFA_8ph8fuMuCmc3YIE0_gwDPUX9Z4o-cIKhsDwOxqNeOlrlIs4MKZxDofpoFGhIvFE2P6YwVoa3LGXo16aeUbaGCaZZCw1tahCTe6Rh_s5DNBFQTBKNneUS-7QPtmS-06OdIo0XxXw1rlu6cnljFAo_vSBwL5-Dx7OjltVDoC0d6WuX5z0r2wO9tSZF-WUJ8z",
    mediaType: "image",
    latitude: 20.2961,
    longitude: 85.8245,
    address: "452 Main St, Alleyway",
    timestamp: "2026-08-07T09:14:00+05:30",
    wasteType: "Illegal Dumping - Plastics",
    aiConfidence: 94,
    estimatedVolume: "2.4 cubic meters",
    estimatedVolumeRange: "2.0 - 2.8 cubic meters",
    severity: "high",
    priorityScore: 88,
    potentialRisk: "Blocked alleyway with spillover into pedestrian path.",
    recommendation: "Assign mini tipper and 4-worker team within 30 minutes.",
    duplicateProbability: 0.18,
    comment: "The pile has grown since yesterday evening.",
    status: "assigned",
    assignedTeam: "team-07",
    beforeImage: "",
    afterImage: "",
    createdAt: "2026-08-07T09:14:00+05:30",
    updatedAt: "2026-08-07T09:45:00+05:30",
    statusTimeline: [
      { status: "submitted", at: "2026-08-07T09:14:00+05:30" },
      { status: "ai_analyzed", at: "2026-08-07T09:15:00+05:30" },
      { status: "under_review", at: "2026-08-07T09:45:00+05:30" },
      { status: "assigned", at: "2026-08-07T10:02:00+05:30" },
    ],
  },
  {
    id: "REP-992A",
    userId: "user-citizen",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAn4vAh1tXzByFd2_YN1MP_18taEOZRY_AqCmGYV9uayb4E-eMfHWL1z3ubnOENxL31QxfhgXFALSyaCLu9WaUvLq-S-EBKTo-DV8Dx8m-4hvssk1b8GCaJhcV3uWStP0FJyJL8Ji9025YovXymtekzYmiZwYleHSpqX1W4W-DrrzTENXpn3Jd4fwAcw2tXBkpNKRrdNM5vlNVuaWQEMz-6HsZq7bBX533yrJeAbFkErCyLiB52H0w5",
    mediaType: "image",
    latitude: 20.3018,
    longitude: 85.8215,
    address: "Behind City Hospital, Sector 2",
    timestamp: "2026-08-07T11:20:00+05:30",
    wasteType: "Medical Waste Dumping",
    aiConfidence: 97,
    estimatedVolume: "3.1 cubic meters",
    estimatedVolumeRange: "2.8 - 3.5 cubic meters",
    severity: "critical",
    priorityScore: 96,
    potentialRisk: "Hazardous material near public health facility.",
    recommendation: "Escalate to hazardous waste unit immediately.",
    duplicateProbability: 0.42,
    comment: "Sharp materials and red bags are visible.",
    status: "under_review",
    assignedTeam: null,
    beforeImage: "",
    afterImage: "",
    createdAt: "2026-08-07T11:20:00+05:30",
    updatedAt: "2026-08-07T11:22:00+05:30",
    statusTimeline: [
      { status: "submitted", at: "2026-08-07T11:20:00+05:30" },
      { status: "ai_analyzed", at: "2026-08-07T11:22:00+05:30" },
      { status: "under_review", at: "2026-08-07T11:26:00+05:30" },
    ],
  },
  {
    id: "REP-18012",
    userId: "user-citizen",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA-9bag6nSlRBRCsmFgQ72r4EMJ7UXzAIWvDtFoqdovIU-23PWxh4OlcT8RkaoLpOJ1EXByvV-SgNXTK-2dw67dgSXilFUesZJdOUFUpoe9-PjD-fMKq7kINkq6XYjQRKYoV15Wh5RB4zueZg9s5HcrpgnHfrWRP2D6-quFz_0HG26MGyv_Sjh-YnT4rEMdz3zmvl3pooj-9lgdfWR3dRaUau2qYEnDs-4Pi4tGvn9UFsKmYmszRKrb",
    mediaType: "image",
    latitude: 20.2955,
    longitude: 85.831,
    address: "Centennial Park",
    timestamp: "2026-08-05T14:32:00+05:30",
    wasteType: "Overflowing Bins",
    aiConfidence: 89,
    estimatedVolume: "1.1 cubic meters",
    estimatedVolumeRange: "0.8 - 1.4 cubic meters",
    severity: "medium",
    priorityScore: 63,
    potentialRisk: "Overflow is attracting flies near a public walkway.",
    recommendation: "Standard truck and two-worker pickup this shift.",
    duplicateProbability: 0.12,
    comment: "The bin is full every evening.",
    status: "resolved",
    assignedTeam: "team-03",
    beforeImage: "",
    afterImage:
      "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-08-05T14:32:00+05:30",
    updatedAt: "2026-08-06T10:15:00+05:30",
    statusTimeline: [
      { status: "submitted", at: "2026-08-05T14:32:00+05:30" },
      { status: "ai_analyzed", at: "2026-08-05T14:34:00+05:30" },
      { status: "under_review", at: "2026-08-05T14:50:00+05:30" },
      { status: "assigned", at: "2026-08-05T15:05:00+05:30" },
      { status: "en_route", at: "2026-08-05T15:15:00+05:30" },
      { status: "cleanup_in_progress", at: "2026-08-05T15:32:00+05:30" },
      { status: "verification", at: "2026-08-05T16:10:00+05:30" },
      { status: "resolved", at: "2026-08-06T10:15:00+05:30" },
    ],
  },
];

export const hotspotData = [
  { name: "Unit 4 Market", severity: "high", complaints: 18 },
  { name: "City Hospital Sector 2", severity: "critical", complaints: 7 },
  { name: "Janpath Road", severity: "medium", complaints: 11 },
];

export const draftTemplate = {
  image: "",
  video: "",
  mediaType: "image",
  imageName: "",
  location: null,
  comment: "",
  aiResult: null,
  duplicateMatch: null,
  analysisStage: "",
};

